"""
Constants shared through the application and API
"""

OK = 'OK'

EXEC_IDLE = 'STATUS_IDLE'
EXEC_RUNNING = 'STATUS_RUNNING'
EXEC_ABORTED = 'STATUS_ABORTED'
EXEC_FINISHED = 'STATUS_FINISHED'
EXEC_BEGIN_FAILED = 'EXEC_BEGIN_FAILED'

BATCH_NO_DATA = 'BATCH_NO_DATA'
BATCH_NOT_VALID = 'BATCH_NOT_VALID'
BATCH_NOT_LOADED = 'BATCH_NOT_LOADED'
BATCH_NOT_NORMALIZED = 'BATCH_NOT_NORMALIZED'

TASK_ERROR_IGNORED = 'STATUS_ERROR_IGNORED'

PLUG_APPLY_MISSING = 'PLUG_APPLY_MISSING'
PLUG_COMMAND_MISSING = 'PLUG_COMMAND_MISSING'
PLUG_COMMAND_NOT_STR = 'PLUG_COMMAND_NOT_STR'
PLUG_VALIDATE_MISSING = 'PLUG_VALIDATE_MISSING'
PLUG_NORMALIZE_MISSING = 'PLUG_NORMALIZE_MISSING'

STATE_ABSENT = 'STATE_ABSENT'
STATE_PRESENT = 'STATE_PRESENT'
STATE_DIRECTORY = 'STATE_DIRECTORY'
STATE_ALREADY_EXISTS = 'STATE_ALREADY_EXISTS'
STATE_FORCE_REINSTALL = 'STATE_FORCE_REINSTALL'

TAG_ADMIN = 'admin'
TAG_COMMON = 'common'

VALID_NAME_MISSING = 'VALID_NAME_MISSING'
VALID_ICON_MISSING = 'VALID_ICON_MISSING'
VALID_TAGS_MISSING = 'VALID_TAGS_MISSING'
VALID_TAGS_NOT_LIST = 'VALID_TAGS_NOT_LIST'
VALID_TASKS_MISSING = 'VALID_TASKS_MISSING'
VALID_TASKS_NOT_LIST = 'VALID_TASKS_NOT_LIST'
VALID_NAME_NOT_STRING = 'VALID_NAME_NOT_STRING'
VALID_TASK_PLUGIN_NOT_FOUND = 'VALID_TASK_PLUGIN_NOT_FOUND'
