import platform

OK = "OK"
ERROR_IGNORED = "ERROR_IGNORED"

TAG_ADMIN = 'admin'

STATE_PRESENT = "present"
STATE_ABSENT = "absent"
STATE_LATEST = "latest"
STATE_FORCE_REINSTALL = "forcereinstall"
STATE_DIRECTORY = "directory"

NAME_MISSING = 'NAME_MISSING'
NAME_NOT_STRING = 'NAME_NOT_STRING'
ICON_MISSING = 'ICON_MISSING'
TAGS_MISSING = 'TAGS_MISSING'
TAGS_NOT_LIST = 'TAGS_NOT_LIST'
TASKS_MISSING = 'TASKS_MISSING'
TASKS_NOT_LIST = 'TASKS_NOT_LIST'
TASK_PLUGIN_NOT_FOUND = 'TASK_PLUGIN_NOT_FOUND'

ASYNC_EXEC_READY = "ASYNC_EXEC_READY"
ASYNC_EXEC_RUNNING = "ASYNC_EXEC_RUNNING"
ASYNC_EXEC_FINISHED = "ASYNC_EXEC_FINISHED"

OS_IS_WINDOWS = platform.system() == 'Windows'
